CREATE DATABASE ProyectoPanaderia;
USE ProyectoPanaderia;
-- La tabla cliente va dirigida a los compradores, más no, al cliente como dueño de la panaderia
CREATE TABLE Cliente (
ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_CLI VARCHAR(20) NOT NULL,
TELEFONO_CLI CHAR(20) NOT NULL,
EMAIL_CLI VARCHAR(20) NOT NULL,
ROL ENUM('CLIENTE','ADMINISTRADOR'),
CONTRASEÑA_CLI INTEGER NOT NULL
);
CREATE TABLE Administrador(
ID_ADMIN INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_ADMIN VARCHAR(20) NOT NULL,
TELEFONO_ADMIN CHAR(20),
EMAIL_ADMIN VARCHAR(20),
CONTRASEÑA_ADMIN INTEGER NOT NULL,
ROL ENUM('CLIENTE','ADMINISTRADOR')
);
CREATE TABLE Proveedor(
ID_PROV INT PRIMARY KEY AUTO_INCREMENT,
NUMERO_PEDIDO TINYINT(200) NOT NULL,
NOMBRE_RROV VARCHAR(20) NOT NULL,
TELEFONO_PROV CHAR(20) NOT NULL,
EMAIL_PROV VARCHAR(20) NOT NULL,
FECHA_PEDIDO DATE NOT NULL
);
-- EL TIPO DE INGREDIENTE ES LA CATEGORÍA DEL PRODUCTO EJ(LECHE(ALQUERIA), MANTEQUILLA(LA FINA), ETC..)
CREATE TABLE Ingrediente(
ID_INGREDIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_INGREDIENTE VARCHAR(20) NOT NULL,
CANTIDAD INT NOT NULL,
TIPO_INGREDIENTE VARCHAR(20) NOT NULL, 
FECHA_INGRESO_INGREDIENTE DATETIME NOT NULL,
FECHA_VENCIMIENTO_INGREDIENTE DATETIME NOT NULL
);
CREATE TABLE Orden_Salida(
ID_FACTURA INT PRIMARY KEY AUTO_INCREMENT,
FECHA_FACTURACION DATETIME NOT NULL
);
CREATE TABLE Producto(
ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_PRODUCTO VARCHAR(20) NOT NULL,
PRODUCTO_STOCK_MAX INT AUTO_INCREMENT NOT NULL,
PRODUCTO_STOCK_MIN INT NOT NULL,
PRECIO_PRODUCTO INT NOT NULL,
FECHA_VENCIMIENTO_PRODUCTO DATE NOT NULL,
FECHA_INGRESO_PRODUCTO DATE NOT NULL,
TIPO_PRODUCTO_MARCA VARCHAR(20) NOT NULL
);
CREATE TABLE Pedido(
ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
FECHA_INGRESO DATETIME NOT NULL,
FECHA_ENTREGA DATETIME NOT NULL,
TOTAL_PRODUCTOS INT NOT NULL
);

INSERT INTO Administrador (ID_ADMIN, NOMBRE_ADMIN) 
VALUES ('1',
		'DAMIAN AVILA'
        );
INSERT INTO Cliente(ID_CLI, NOMBRE_CLI, TELEFONO_CLI, EMAIL_CLI, ROL) 
VALUES ('CLI_1', 
		'ANA GOYENECHE',
        '0000000',
        'ANA@GMAIL.COM',
        'CLIENTE'
        );
INSERT INTO Ingredientes (ID_INGREDIENTES, NOMBRE_INGREDIENTE, CANTIDAD, TIPO_INGREDIENTE, FECHA_INGRESO_INGREDIENTE, FECHA_VENCIMIENTO_INGREDIENTE) VALUES 
	   ('1', 'HARINA PAN', '50', 'HARINA DE TRIGO','19-05-2025','19-05-2025'),
		('2', 'LECHE', '75', '1L','19-05-20');
        